version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "8181:15672"
      - "5672:5672"
    networks:
      - rabbitmq-network
    restart: always

networks:
  rabbitmq-network:
    # external:
    #   name: host
  # sender:
  #   build: ./sender
  #   restart: always
  #   links:
  #     - rabbitmq
  #   depends_on:
  #     - rabbitmq
  # consumer:
  #   build: ./consumer
  #   restart: always
  #   links:
  #     - rabbitmq
  #   depends_on:
  #     - rabbitmq
  #     - sender
